/**
 * Registry of the supplied artwork used on the site.
 *
 * The .webp files are optimised derivatives generated by `npm run art` from the
 * originals in ../EEMS_BMFX_Website_Build_Pack/original-assets (never edited).
 * To replace a piece: swap the original, re-run `npm run art`, and update the
 * alt text below if the picture itself changed.
 */
import characterPortrait from '@/assets/art/character-portrait.webp'
import eemojiAnnoyed from '@/assets/art/eemoji-annoyed.webp'
import eemojiGrin from '@/assets/art/eemoji-grin.webp'
import eemojiSmirk from '@/assets/art/eemoji-smirk.webp'
import eemojiWorried from '@/assets/art/eemoji-worried.webp'
import eemsAtmosphere from '@/assets/art/eems-atmosphere.webp'
import eemsCharacters from '@/assets/art/eems-characters.webp'
import eemsPortrait from '@/assets/art/eems-portrait.webp'
import eemsWordmark from '@/assets/art/eems-wordmark.webp'
import merchArtwork from '@/assets/art/merch-artwork.webp'
import swagBag from '@/assets/art/swag-bag.webp'
import symptoms from '@/assets/art/symptoms.webp'
import type { Artwork, ArtworkId } from './types'

export const artwork: Record<ArtworkId, Artwork> = {
  eemsWordmark: {
    src: eemsWordmark,
    alt: 'EEMS',
    sourceFile: 'wallpaper.png',
    transparent: true,
  },
  eemsPortrait: {
    src: eemsPortrait,
    alt: 'Edited portrait of EEMS in an EEMS beanie, lit in red and blue',
    sourceFile: 'EEMS-ghoul.png',
    focal: '50% 35%',
  },
  merchArtwork: {
    src: merchArtwork,
    alt: 'Psychedelic illustration of a curly-haired character in a green tracksuit relaxing in a purple meadow with a rabbit and a squirrel, blowing smoke that spells EEMS under an orange and violet sky',
    sourceFile: 'BACK-MERCH.png',
    focal: '50% 24%',
  },
  eemsCharacters: {
    src: eemsCharacters,
    alt: 'Colourful bubble letters spelling EEMS, with a koala and a raccoon sitting on top and a rabbit on each side',
    sourceFile: 'Untitled45.png',
    transparent: true,
  },
  swagBag: {
    src: swagBag,
    alt: 'Chrome SWAG BAG lettering above a silver hatchback parked in long grass under a glowing orange sky',
    sourceFile: 'swagbag-s3.png',
    focal: '50% 48%',
  },
  eemsAtmosphere: {
    src: eemsAtmosphere,
    alt: 'Glowing white EEMS lettering over a night landscape with a rainbow, a tree and two figures',
    sourceFile: 'eems.png',
    focal: '50% 50%',
  },
  symptoms: {
    src: symptoms,
    alt: 'SYMPTOMS artwork: a hand-lettered lilac SYMPTOMS title and the name EEMS above a smiling portrait with curly green hair',
    sourceFile: 'Symptoms-album-art.png',
    focal: '50% 22%',
  },
  eemojiSmirk: {
    src: eemojiSmirk,
    alt: 'Illustrated character with curly pink hair and a nose ring, smirking',
    sourceFile: 'Eemsojis_20240801120211.png',
    transparent: true,
  },
  eemojiAnnoyed: {
    src: eemojiAnnoyed,
    alt: 'Illustrated character with curly pink hair and a nose ring, frowning under an anger mark',
    sourceFile: 'Eemsojis_20240801120149.png',
    transparent: true,
  },
  eemojiWorried: {
    src: eemojiWorried,
    alt: 'Illustrated character with curly pink hair and a nose ring, wide-eyed and worried with a sweat drop',
    sourceFile: 'Eemsojis_20240801120204.png',
    transparent: true,
  },
  eemojiGrin: {
    src: eemojiGrin,
    alt: 'Illustrated character with curly pink hair and a nose ring, grinning with eyes closed',
    sourceFile: '5.PNG',
    transparent: true,
  },
  characterPortrait: {
    src: characterPortrait,
    alt: 'Illustrated character with curly pink hair and a nose ring, smirking, on a mauve background',
    sourceFile: '5.gif',
    focal: '50% 42%',
  },
}
