/**
 * EEMS merch: copy for the merch page and the Shopify Buy Button settings.
 * Products, variants, prices and stock are loaded live from Shopify, so they
 * are never duplicated here. See docs/merch.md for the store setup.
 */
import type { ArtworkId } from './types'

export const merch = {
  heading: 'Merch',
  eyebrow: 'EEMS merch',
  intro: 'Tees, hoodies and sweatpants featuring EEMS artwork. Pick your colour and size below.',
  checkoutNote: 'Secure checkout with Shopify. Shipping is calculated at checkout.',
  collectionHeading: 'Shop the collection',
  /** Supplied merch artwork shown large on the merch page. */
  artwork: 'merchArtwork' satisfies ArtworkId as ArtworkId,
  artworkContext: 'Artwork for merch connected to the upcoming EEMS album.',
  shopify: {
    domain: 'rfrjfs-u0.myshopify.com',
    /**
     * Public Storefront token generated by Shopify's Buy Button editor. It is
     * meant to be in page code. Never replace it with an Admin API token.
     */
    storefrontAccessToken: 'faa6883c86b66b9dbe41fc98a9545412',
    /** The "EEMS merch" collection. Add products to it in Shopify to list them here. */
    collectionId: '695390503244',
    /** £{{amount}}, URL-encoded as the Buy Button expects. */
    moneyFormat: '%C2%A3%7B%7Bamount%7D%7D',
    sdkUrl: 'https://sdks.shopifycdn.com/buy-button/latest/buy-button-storefront.min.js',
  },
} as const
